import numpy as np
import matplotlib.pyplot  as plt 
import matplotlib.colors
norm = plt.Normalize(-2,2)
cmap_hu = plt.cm.get_cmap('tab20')#matplotlib.colors.LinearSegmentedColormap.from_list("", ["#073B45","#453E00", "#918407"], 16)
cmap_mi = plt.cm.get_cmap('tab20')#matplotlib.colors.LinearSegmentedColormap.from_list("", ["#FF7759","#CD0BAE", "#32148C"], 16)
cmap_ma = plt.cm.get_cmap('tab20')#matplotlib.colors.LinearSegmentedColormap.from_list("", ["#087F8C","#7FDB91", "#7FDB0D"],16)
params_ctx = {
        "model_dir": "GOOD_Resub_CTX/",
        "multispecies":True,
        "brain_region": "CTX",
        "list_no_mi": [2, 3, 5,6, 9, 10, 11, 13, 14, 15, 16],#1, 2, 4, 5, 8, 9, 10, 11, 12, 15],
        "list_no_hu" :[1, 4, 8, 12],#3, 7, 13, 14],
         "list_no_ma" :[1, 4, 8, 12],#3, 7, 13, 14],
         "order" : [7,1, 4, 8,12,2,3,5,6, 9, 10,11,13, 14, 15,16],#ctx

         "mapping":{9:"HuMu1", 7: "A1", 4:"Mu2", 1:"Mu1",
                        8:"Mu3", 12:"Mu4", 2:"P1", 3:"P2", 
                     5:"P3", 6:"P4", 9:"P5",10:"P6",11:"P7", 
                     13: "P8", 14:"P9",
                             15:"P10", 16:"P11"},
         #"mapping" : {6:"A1", 3:"Mu1", 7:"Mu2", 13:"Mu3",
         #             14:"Mu4", 1:"P1", 
         #             2:"P2", 4:"P3", 5:"P4",8:"P5",
         #             9:"P6", 10: "P7", 11:"P8",
         #             12:"P9", 15:"P10"},
         "dico_color":{"P9":"#7680B6", "A1":"#B1B1B1",
                        "Mu1":"#D64D86", "Mu2":"#D69ABF",#EED4B8
                         "Mu3":"#ECB4ED", "Mu4":"#FDB0C4", 
                         "P1":"#E1C847", "P10":"#4F4991",
                         "P2":"#DBDC8F", "P3":"#D6F0D6", "P11":"#4BA849",
                        "P4":"#A7D0BB","P5":"#499186",#"#0F9168"
                        "P6":"#9BCFD7", "P7":"#C4EEFF",
                        "P8":"#9DB7DA"},#8A9E00",#"#4BA849",
                        #},
         #"dico_color":{"P9":"#7680B6", "A1":"#B1B1B1",
         #               "Mu1":"#D64D86", "Mu2":"#D69ABF",#EED4B8
         #                "Mu3":"#ECB4ED", "Mu4":"#FDB0C4", 
         #                "P1":"#E1C847", 
         #               "P2":"#DBDC8F", "P3":"#D6F0D6",
         #               "P4":"#A7D0BB","P5":"#499186",#"#0F9168"
         #               "P6":"#9BCFD7", "P7":"#C4EEFF",
         #               "P8":"#9DB7DA",#8A9E00",#"#4BA849",
         #               "P10":"#4F4991"},
         "dico_offset_x":{"A1":0, "Mu1":0, "Mu2":0,
                     "Mu3":0, "P2":0,
                     "P8":0, "P9":0, "P10":0,"P11":0,
                          "P3":0,"P4":0,"P5":0,
                            "P6":0, "P7":0, "P1":0,
                            },
         "dico_offset_y":{"A1":0, "Mu1":0, "Mu2":0,
                         "Mu3":0, "P2":0, 
                     "P8":0, "P9":0, "P10":0,"P11":0,
                          "P3":0,"P4":0,"P5":0,
                            "P6":0, "P7":0, "P1":0,
                            },
         #"dico_offset_x":{"P9":-2, "A1":0, "Mu1":6, "Mu2":6,
         #                "Mu3":0, "Mu4":-2, "P2":-2, 
         #                "P8":0, "P3":0,"P4":-3,"P5":-10,
         #                   "P6":3, "P7":0, "P1":3,
         #                   "P10":-3},
         #"dico_offset_y":{"P9":0, "A1":-2, "Mu1":4, "Mu2":0,
         #                 "Mu3":0, "Mu4":0, "P2":4, 
         #                 "P8":0, "P3":3,"P4":0,"P5":0,
         #                 "P6":0, "P7":-2, "P1":4, "P10":-2},
         #"color_map_species":{"Hu":"#073B45", 
         #               "Mu":"#FF5A5F", "Ma":"#087E8B"},
         "color_map_species":{"Hu":"#87C38F", 
                        "Mu":"#DA2C38", "Ma":"#126D80"},
         "color_batch_effect": ["#ffd8b1", "#e6194B",
                                "#2EC785", "#ffe119",
                                "#4363d8", "#911eb4"],
         "color_map_ba":{"CTX":"#EBC611", 
                            "HIPP":"#681B9E",
                            "NSTR":"#1C81EB"},
         "clusters_mo":["P%d"%k for k in range(1,12)],
         "clusters_mi":["Mu1","Mu2", "Mu3","Mu4", "A1"]

         }

params_hipp = {
        "model_dir": "GOOD_Resub_HIPP/",
        "brain_region": "HIPP",
        "multispecies":True,
        "list_no_mi":[1, 3, 5, 9, 10, 11], #2, 5, 6, 7, 10, 11],
        "list_no_hu":[2, 6, 7, 8, 14], #1, 4, 8, 9, 14], 
         "list_no_ma" :range(1,15),#,12, 13, 14],
         #"order" :[3, 12, 13, 2,5, 6, 7, 10, 11, 1, 4, 8, 9, 14], 
         "order" :[4,12, 13,2,7,8,14,6,1,3,5,9,10,11],#hipp, 
        "mapping":{5:"H-Hu3", 2:"H-Mu1", 9:"H-Hu4",12:"H-HuMu2",
                        13:"H-HuMu3", 1:"H-Hu1", 14:"H-Mu4",10:"H-Hu5",
                        11:"H-Hu6", 4:"H-HuMu1", 3:"H-Hu2",
                        6:"H-Mu5",8:"H-Mu3", 7: "H-Mu2",
                                      },
         #"mapping" :{3:"H-HuMu1", 12:"H-HuMu2", 13:"H-HuMu3", 2:"H-Hu1",
         #           5:"H-Hu2", 6:"H-Hu3", 7:"H-Hu4", 10:"H-Hu5",11:"H-Hu6",
         #           1:"H-Mu1", 4: "H-Mu2", 8:"H-Mu3",
         #                      9:"H-Mu4", 14:"H-Mu5"},
         "clusters_mo":[],
         "clusters_mi":[],#"H-HuMu%d"%k for k in range(1,4)],
         "dico_color":{"H-HuMu1":'#8D7569', "H-HuMu2":"#B37D46",
             "H-HuMu3":"#D98423", "H-HuMu4":"orange",
                        "H-HuMu3":"#D98423", "H-Mu1":"#E8EAD1",
                     "H-Mu2":"#CDDA9F", "H-Mu3":"#B9CBB6",
                     "H-Mu4":"#6A9C21", 
                    "H-Mu5":"#91BD68", #"H-Mu6":"#B7DEAE",
                    "H-Hu1":"#F4C9FF","H-Hu2":"#D791B5",#"#0F9168"
                    "H-Hu3":"#91498B", "H-Hu4":"#9C2020",
                    "H-Hu5":"#BA9FD8","H-Hu6":"#785A9B"
                                                },
         #"dico_color":{"H-HuMu1":'#8D7569', "H-HuMu2":"#B37D46",
         #               "H-HuMu3":"#D98423", "H-Mu1":"#E8EAD1",
         #            "H-Mu2":"#CDDA9F", "H-Mu3":"#B9CBB6",
         #            "H-Mu4":"#6A9C21", 
         #           "H-Mu5":"#91BD68", "H-Mu6":"#B7DEAE",
         #           "H-Hu1":"#F4C9FF","H-Hu2":"#D791B5",#"#0F9168"
         #           "H-Hu3":"#91498B", "H-Hu4":"#9C2020",
         #           "H-Hu5":"#BA9FD8","H-Hu6":"#785A9B"
         #                                       },
         #"color_map_species":{"Hu":"#073B45", "Mu":"#FF5A5F", "Ma":"#087E8B"},
         "color_map_species":{"Hu":"#87C38F", 
                        "Mu":"#DA2C38", "Ma":"#126D80"},
         "color_batch_effect": ["#ffd8b1", "#e6194B",
                                "#2EC785", "#ffe119", 
                                "#4363d8", "#911eb4"],
         "color_map_ba":{"CTX":"#EBC611",
                        "HIPP":"#681B9E",
                        "NSTR":"#1C81EB"},
         "dico_offset_x":{"H-HuMu1":0, "H-HuMu2":0, "H-HuMu3":0,
                         "H-Mu5":0,
                         "H-Mu1":0, "H-Mu2":0, "H-Mu3":0, "H-Mu4":0, 
                        "H-Mu5":0, "H-Mu6":-0,"H-Hu1":0,"H-Hu2":0,
                        "H-Hu3":0, "H-Hu5":0, "H-Hu4":0,"H-Hu6":0, 
                                                    },
         "dico_offset_y":{"H-HuMu1":0, "H-HuMu2":0, "H-HuMu3":0,
                         "H-Mu5":0,
                         "H-Mu1":0, "H-Mu2":0, "H-Mu3":0, "H-Mu4":0, 
                        "H-Mu5":0, "H-Mu6":-0,"H-Hu1":0,"H-Hu2":0,
                        "H-Hu3":0, "H-Hu5":0, "H-Hu4":0,"H-Hu6":0, 
                                                    }

         }
params_str = {
        "model_dir": "GOOD_Resub_NSTR/",
        "brain_region": "NSTR",
        "multispecies":True,
        "list_no_mi":[it for it in range(1,16)],#,12, 13, 14, 15],
        "list_no_hu":[], 
         "list_no_ma" :[],
         #"order" :[1,2,3,4,5,6,7,8,9,10,11,12, 13, 14, 15],
         "order" :[it for it in np.arange(1,16)], 
        #"mapping":{it+1:it+1 for it in np.arange(11)}

        "mapping": {k:"NS-P%d"%k for k in range(1,16)},
                   # 13:"S-HuMa13",
                   # 14:"S-HuMa14", 15:"S-HuMa15"},
         "clusters_mi":[],
         "clusters_mo":["NS-P%d"%k for k in np.arange(1,16)],
         "dico_color":{"NS-P1":"#FFD20D", "NS-P2":"#BA7687",
                        "NS-P3":"#4FDE0B", "NS-P4":"#FFC9FB",#EED4B8
                         "NS-P5":"#D602F7", "NS-P6":"#F72902",
                         "NS-P7":"#F99339", 
                        "NS-P8":"#9077BB","NS-P9":"#FFD2AB",
                        "NS-P10":"#CDC9FF","NS-P11":"#F089C0",
                        "NS-P12":"#00ABF5",#"#0F9168"
                        "NS-P13":"#00F5C8", "NS-P14":"#C9FFFB",
                        "NS-P15":"#86AEC4",#8A9E00",#"#4BA849",
                                                    },
         "color_batch_effect": ["#ffd8b1", "#e6194B",
                                "#2EC785", "#ffe119", 
                                "#4363d8", "#911eb4"],
         #"color_map_species":{"Hu":"#073B45", "Mu":"#FF5A5F", "Ma":"#087E8B"},
         "color_map_species":{"Hu":"#87C38F", 
                        "Mu":"#DA2C38", "Ma":"#126D80"},
         "color_map_ba":{"CTX":"#EBC611",
                        "HIPP":"#681B9E",
                        "NSTR":"#1C81EB"},
         "dico_offset_x":{"NS-P%s"%str(it+1):0 for it in np.arange(15)},
         "dico_offset_y":{"NS-P%s"%str(it+1):0 for it in np.arange(15)},
         #"dico_offset_x":{"S-HuMa1":4, "S-HuMa2":-9, "S-HuMa3":0, 
         #                 "S-HuMa4":5, "S-HuMa5":-9, "S-HuMa6":12, 
         #                 "S-HuMa7":-5, "S-HuMa8":0, "S-HuMa9":0,
         #                 "S-HuMa10":-5,"S-HuMa11":12,#"#0F9168"
         #                "S-HuMa12":12, "S-HuMa13":0,
         #                "S-HuMa14":-5,"S-HuMa15":0
         #                                           },
         #"dico_offset_y":{"S-HuMa1":5, "S-HuMa2":-5, "S-HuMa3":0,
         #               "S-HuMa4":-5, "S-HuMa5":0, "S-HuMa6":-4, 
         #               "S-HuMa7":0, "S-HuMa8":5, "S-HuMa9":0,
         #               "S-HuMa10":0,"S-HuMa11":0,#"#0F9168"
         #               "S-HuMa12":0, "S-HuMa13":-12, "S-HuMa14":0,
         #               "S-HuMa15":8 }
         }
params_ctx_Hu = {
        "model_dir": "Monospecies_Hu_CTX/",
        "brain_region": "CTX",
        "multispecies":False,
        "Species": "Hu",
        "list_no_mi":[],
        "list_no_hu" :[],
         "list_no_ma" :[],
         "order" : [it for it in np.arange(17)],

         "mapping" : {it:"C-H%s"%str(it) for it in np.arange(17)},
         "dico_color":{"C-H%s"%str(it):cmap_hu(it) for it in np.arange(17)},
         "dico_offset_x":None,
         "dico_offset_y":None,
         #"color_map_species":{"Hu":"#073B45", "Mu":"#FF5A5F", "Ma":"#087E8B"},
         "color_map_species":{"Hu":"#87C38F", 
                        "Mu":"#DA2C38", "Ma":"#126D80"},
         "color_batch_effect": ["#ffd8b1", "#e6194B",
                                "#2EC785", "#ffe119",
                                "#4363d8", "#911eb4"],
         "color_map_ba":{"CTX":"#EBC611", 
                            "HIPP":"#681B9E",
                            "NSTR":"#1C81EB"},
         "clusters_mo":[],
         "clusters_mi":[]

         }

params_hipp_Hu = {
        "model_dir": "ae_Hu_HIPP/",
        "brain_region": "HIPP",
        "multispecies":False,
        "Species": "Hu",
        "list_no_mi":[],
        "list_no_hu" :[],
         "list_no_ma" :[],
         "order" : [it for it in range(16)],

         "mapping" : {it:"H-H%s"%str(it) for it in range(16)},
         "dico_color":{"H-H%s"%str(it):cmap_hu(it) for it in range(16)},
         "dico_offset_x":None,
         "dico_offset_y":None,
         #"color_map_species":{"Hu":"#073B45", #"Mu":"#FF5A5F", "Ma":"#087E8B"},
         "color_map_species":{"Hu":"#87C38F", 
                        "Mu":"#DA2C38", "Ma":"#126D80"},
         "color_batch_effect": ["#ffd8b1", "#e6194B",
                                "#2EC785", "#ffe119",
                                "#4363d8", "#911eb4"],
         "color_map_ba":{"CTX":"#EBC611", 
                            "HIPP":"#681B9E",
                            "NSTR":"#1C81EB"},
         "clusters_mo":[],
         "clusters_mi":[]

         }
params_nstr_Hu = {
        "model_dir": "ae_Hu_NSTR/",
        "brain_region": "NSTR",
        "multispecies":False,
        "Species": "Hu",
        "list_no_mi":[],
        "list_no_hu" :[],
         "list_no_ma" :[],
         "order" : [it for it in range(16)],

         "mapping" : {it:"NS-H%s"%str(it) for it in range(16)},
         "dico_color":{"NS-H%s"%str(it):cmap_hu(it) for it in range(16)},
         "dico_offset_x":None,
         "dico_offset_y":None,
         #"color_map_species":{"Hu":"#073B45", "Mu":"#FF5A5F", "Ma":"#087E8B"},
         "color_map_species":{"Hu":"#87C38F", 
                        "Mu":"#DA2C38", "Ma":"#126D80"},
         "color_batch_effect": ["#ffd8b1", "#e6194B",
                                "#2EC785", "#ffe119",
                                "#4363d8", "#911eb4"],
         "color_map_ba":{"CTX":"#EBC611", 
                            "HIPP":"#681B9E",
                            "NSTR":"#1C81EB"},
         "clusters_mo":[],
         "clusters_mi":[]

         }
params_nstr_Ma = {
        "model_dir": "ae_Ma_NSTR/",
        "brain_region": "NSTR",
        "multispecies":False,
        "Species": "Ma",
        "list_no_mi":[],
        "list_no_hu" :[],
         "list_no_ma" :[],
         "order" : [it for it in range(17)],

         "mapping" : {it:"NS-Ma%s"%str(it) for it in range(17)},
         "dico_color":{"NS-Ma%s"%str(it):cmap_ma(it) for it in range(17)},
         "dico_offset_x":None,
         "dico_offset_y":None,
         #"color_map_species":{"Hu":"#073B45", "Mu":"#FF5A5F", "Ma":"#087E8B"},
         "color_map_species":{"Hu":"#87C38F", 
                        "Mu":"#DA2C38", "Ma":"#126D80"},
         "color_batch_effect": ["#ffd8b1", "#e6194B",
                                "#2EC785", "#ffe119",
                                "#4363d8", "#911eb4"],
         "color_map_ba":{"CTX":"#EBC611", 
                            "HIPP":"#681B9E",
                            "NSTR":"#1C81EB"},
         "clusters_mi":[],
         "clusters_mo":["C-Ma%s"%str(it) for it in range(16)]

         }

params_ctx_Ma = {
        "model_dir": "Monospecies_Ma_CTX/",
        "brain_region": "CTX",
        "multispecies":False,
        "Species": "Ma",
        "list_no_mi":[],
        "list_no_hu" :[],
         "list_no_ma" :[],
         "order" : [it for it in range(16)],

         "mapping" : {it:"C-Ma%s"%str(it) for it in range(16)},
         "dico_color":{"C-Ma%s"%str(it):cmap_ma(it) for it in range(16)},
         "dico_offset_x":None,
         "dico_offset_y":None,
         #"color_map_species":{"Hu":"#073B45", "Mu":"#FF5A5F", "Ma":"#087E8B"},
         "color_map_species":{"Hu":"#87C38F", 
                        "Mu":"#DA2C38", "Ma":"#126D80"},
         "color_batch_effect": ["#ffd8b1", "#e6194B",
                                "#2EC785", "#ffe119",
                                "#4363d8", "#911eb4"],
         "color_map_ba":{"CTX":"#EBC611", 
                            "HIPP":"#681B9E",
                            "NSTR":"#1C81EB"},
         "clusters_mi":[],
         "clusters_mo":["C-Ma%s"%str(it) for it in range(16)]

         }

params_ctx_Mu = {
        "model_dir": "Monospecies_Mu_CTX/",
        "brain_region": "CTX",
        "multispecies":False,
        "Species": "Mu",
        "list_no_mi":[],
        "list_no_hu" :[],
         "list_no_ma" :[],
         "order" : [it for it in range(16)],

         "mapping" : {it:"C-Mu%s"%str(it) for it in range(16)},
         "dico_color":{"C-Mu%s"%str(it):cmap_mi(it) for it in range(16)},
         "dico_offset_x":None,
         "dico_offset_y":None,
         #"color_map_species":{"Hu":"#073B45", "Mu":"#FF5A5F", "Ma":"#087E8B"},
         "color_map_species":{"Hu":"#87C38F", 
                        "Mu":"#DA2C38", "Ma":"#126D80"},
         "color_batch_effect": ["#ffd8b1", "#e6194B",
                                "#2EC785", "#ffe119",
                                "#4363d8", "#911eb4"],
         "color_map_ba":{"CTX":"#EBC611", 
                            "HIPP":"#681B9E",
                            "NSTR":"#1C81EB"},
         "clusters_mo":[],
        "clusters_mi":["C-Mu%s"%str(it) for it in range(16)]

         }

params_hipp_Mu = {
        "model_dir": "ae_Mu_HIPP/",
        "brain_region": "HIPP",
        "multispecies":False,
        "Species": "Mu",
        "list_no_mi":[],
        "list_no_hu" :[],
         "list_no_ma" :[],
         "order" : [it for it in range(16)],

         "mapping" : {it:"H-Mu%s"%str(it) for it in range(16)},
         "dico_color":{"H-Mu%s"%str(it):cmap_mi(it) for it in range(16)},
         "dico_offset_x":None,
         "dico_offset_y":None,
         #"color_map_species":{"Hu":"#073B45", "Mu":"#FF5A5F", "Ma":"#087E8B"},
         "color_map_species":{"Hu":"#87C38F", 
                        "Mu":"#DA2C38", "Ma":"#126D80"},
         "color_batch_effect": ["#ffd8b1", "#e6194B",
                                "#2EC785", "#ffe119",
                                "#4363d8", "#911eb4"],
         "color_map_ba":{"CTX":"#EBC611", 
                            "HIPP":"#681B9E",
                            "NSTR":"#1C81EB"},
         "clusters_mo":[],
        "clusters_mi":[]

         }
